define:
  - &subreddit-settings
    type: reddit
    collapse-after: 3
    show-thumbnails: true
    style: vertical-list
    show-flairs: true
    cache: 2h
    limit: 10


server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  custom-css-file: /assets/user.css

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
  !include: news.yml
  !include: infosecnews.yml  
  !include: reddit.yml
  !include: geocities.yml  
