- name: Reddit
  columns:
    - size: full
      widgets:
        - type: split-column
          max-columns: 4
          widgets:
            - subreddit: selfhosted
              <<: *subreddit-settings
            - subreddit: cybersecurity
              <<: *subreddit-settings
            - subreddit: linux
              <<: *subreddit-settings
            - subreddit: sysadmin
              <<: *subreddit-settings
            - subreddit: homelab
              <<: *subreddit-settings
            - subreddit: Networking
              <<: *subreddit-settings
            - subreddit: netsec
              <<: *subreddit-settings
            - subreddit: OpenSource
              <<: *subreddit-settings
            - subreddit: Privacy
              <<: *subreddit-settings
            - subreddit: FreeSoftware
              <<: *subreddit-settings
