version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.msxtec.co.uk
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASSWORD=Sink8411!
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      - MAIL_HOST=10.100.1.50
      - MAIL_PORT=25
      - MAIL_FROM=bookstack@msxtec.co.uk
      - MAIL_FROM_NAME=Bookstack
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 4443:443
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=Sink8411!
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=Sink8411!
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
