global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: salter # Change to whatever you like
    static_configs:
      - targets: ['localhost:9090'] #Change this to your server's IP



  - job_name: docker-internal-stock
    static_configs:
      - targets: ['10.50.5.45:9100']

  - job_name: docker-external-logs
    static_configs:
      - targets: ['10.100.1.50:9100']

  - job_name: Nexcloud-AIO
    static_configs:
      - targets: ['10.100.1.52:9100']

  - job_name: pihole-physical
    static_configs:
      - targets: ['10.50.5.200:9100']

  - job_name: diet-pi-vm
    static_configs:
      - targets: ['192.168.4.17:9100']

  - job_name: Docker-internal-P
    static_configs:
      - targets: ['10.50.5.51:9100']

  - job_name: Kasm
    static_configs:
      - targets: ['10.100.1.30:9100']
  
  - job_name: docker-dmz-fo-1
    static_configs:
      - targets: ['10.100.1.48:9100']
  
  - job_name: docker-dmz-fo-2
    static_configs:
      - targets: ['10.100.1.49:9100']      
       


