---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=https://jellyfin.msxtec.co.uk # optional
    volumes:
      - /nfs/data/jellyfin/config:/config
      - /nfs/data/jellyfin/metadata:/metadata
      - /nfs/media:/data/media:ro
      - /opt/jellyfin/cache:/cache
      - /opt/jellyfin/transcodes:/transcodes
    ports:
      - 8096:8096
      - 8920:8920 # optional
      - 7359:7359/udp # optional
      - 1900:1900/udp # optional
    restart: unless-stopped

