version: '3'
services:
  guacdb:
    container_name: guacamoledb
    image: mariadb:10.9.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MariaDBRootPass'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user'
      MYSQL_PASSWORD: 'MariaDBUserPass'
    volumes:
      - './db-data:/var/lib/mysql'
    networks:
      - guac-net   
  guacd:
    container_name: guacd
    image: guacamole/guacd:latest
    restart: unless-stopped
    networks:
      - guac-net  
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - 8070:8080
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacdb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "MariaDBUserPass"
      TOTP_ENABLED: "true"
      SAML_ENABLED: "true"
      EXTENSION_PRIORITY: "*,SAML"
      SAML_IDP_URL: "https://login.microsoftonline.com/ab8f5195-dfd2-4db9-937e-b550ed2fc9f1/saml2"
      SAML_ENTITY_ID: "https://remote.truepb.net/guacamole/"
      SAML_CALLBACK_URL: "https://remote.truepb.net/guacamole/"
      SAML_IDP_METADATA_URL: "https://login.microsoftonline.com/ab8f5195-dfd2-4db9-937e-b550ed2fc9f1/federationmetadata/2007-06/federationmetadata.xml?appid=840bc903-685c-4231-9d4b-383e27c614e2"
    depends_on:
      - guacdb
      - guacd
    volumes:
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    networks:
      - guac-net

volumes:
  db-data:

networks:
  guac-net:
    external: true
